spring.application.name=pt
# AWS & DynamoDB Configuration
aws.region=${AWS_REGION:us-east-1}
aws.credentials.access-key=${AWS_ACCESS_KEY_ID:ID_AWS}
aws.credentials.secret-key=${AWS_SECRET_ACCESS_KEY:KEY_AWS}

# DynamoDB Properties
# Use http://localhost:8000 for local development with DynamoDB Local
# For production AWS environment, use: https://dynamodb.us-east-1.amazonaws.com
aws.dynamodb.endpoint=${AWS_DYNAMODB_ENDPOINT:http://localhost:8000}
aws.dynamodb.table-name=${AWS_DYNAMODB_TABLE_NAME:franchise}

